-- Auto-generated shim. Canonical source is src/proxy.lua.
-- DO NOT EDIT THIS FILE. Edit src/proxy.lua instead.
-- Regenerate with: tools/regen-shims.sh
-- Enforced by:    tools/check-file-sync.sh
--
-- Rationale: running `luajit src/main.lua` without installing the rockspec
-- means `require("lunarblock.proxy")` resolves via luajit's default
-- `./?.lua` search pattern to this file. We forward to the canonical
-- src/ copy via dofile using a path derived from this shim's own location.
local dir = debug.getinfo(1, "S").source:match("@?(.*/)") or ""
return dofile(dir .. "../src/proxy.lua")
