-- Auto-generated shim. Canonical source is src/utxo.lua.
-- DO NOT EDIT THIS FILE. Edit src/utxo.lua instead.
-- See tools/check-file-sync.sh for the enforcement check.
--
-- Rationale: running `luajit src/main.lua` without installing the rockspec
-- means `require("lunarblock.utxo")` resolves via luajit's default
-- `./?.lua` search pattern to this file. We forward to the canonical
-- src/ copy via dofile using a path derived from this shim's own location.
local dir = debug.getinfo(1, "S").source:match("@?(.*/)") or ""
return dofile(dir .. "../src/utxo.lua")
