describe("types", function()
  local types

  setup(function()
    types = require("lunarblock.types")
  end)

  describe("hash256", function()
    it("creates a hash256 from 32 bytes", function()
      local bytes = string.rep("\x00", 32)
      local h = types.hash256(bytes)
      assert.is_table(h)
      assert.equal("hash256", h._type)
      assert.equal(32, #h.bytes)
    end)

    it("rejects invalid byte lengths", function()
      assert.has_error(function()
        types.hash256("short")
      end, "hash256 requires exactly 32 bytes")

      assert.has_error(function()
        types.hash256(string.rep("\x00", 31))
      end, "hash256 requires exactly 32 bytes")

      assert.has_error(function()
        types.hash256(string.rep("\x00", 33))
      end, "hash256 requires exactly 32 bytes")
    end)

    it("converts to hex display format (big-endian)", function()
      -- Genesis block hash in little-endian (wire format)
      local le_bytes = string.char(
        0x6f, 0xe2, 0x8c, 0x0a, 0xb6, 0xf1, 0xb3, 0x72,
        0xc1, 0xa6, 0xa2, 0x46, 0xae, 0x63, 0xf7, 0x4f,
        0x93, 0x1e, 0x83, 0x65, 0xe1, 0x5a, 0x08, 0x9c,
        0x68, 0xd6, 0x19, 0x00, 0x00, 0x00, 0x00, 0x00
      )
      local h = types.hash256(le_bytes)
      local hex = types.hash256_hex(h)
      assert.equal("000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f", hex)
    end)

    it("parses from hex display format (big-endian)", function()
      local hex = "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"
      local h = types.hash256_from_hex(hex)
      assert.equal("hash256", h._type)
      -- Converting back to hex should give the same string
      assert.equal(hex, types.hash256_hex(h))
    end)

    it("creates zero hash", function()
      local h = types.hash256_zero()
      assert.equal("hash256", h._type)
      assert.equal(string.rep("\0", 32), h.bytes)
      assert.equal(string.rep("0", 64), types.hash256_hex(h))
    end)

    it("compares hashes for equality", function()
      local h1 = types.hash256(string.rep("\x01", 32))
      local h2 = types.hash256(string.rep("\x01", 32))
      local h3 = types.hash256(string.rep("\x02", 32))

      assert.is_true(types.hash256_eq(h1, h2))
      assert.is_false(types.hash256_eq(h1, h3))
    end)

    it("round-trips hex conversion", function()
      local original_hex = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
      local h = types.hash256_from_hex(original_hex)
      assert.equal(original_hex, types.hash256_hex(h))
    end)
  end)

  describe("hash160", function()
    it("creates a hash160 from 20 bytes", function()
      local bytes = string.rep("\x00", 20)
      local h = types.hash160(bytes)
      assert.is_table(h)
      assert.equal("hash160", h._type)
      assert.equal(20, #h.bytes)
    end)

    it("rejects invalid byte lengths", function()
      assert.has_error(function()
        types.hash160("short")
      end, "hash160 requires exactly 20 bytes")
    end)
  end)

  describe("outpoint", function()
    it("creates an outpoint", function()
      local h = types.hash256(string.rep("\xab", 32))
      local op = types.outpoint(h, 5)
      assert.equal("outpoint", op._type)
      assert.equal(h, op.hash)
      assert.equal(5, op.index)
    end)
  end)

  describe("txin", function()
    it("creates a txin with defaults", function()
      local h = types.hash256(string.rep("\x00", 32))
      local op = types.outpoint(h, 0)
      local inp = types.txin(op)

      assert.equal("txin", inp._type)
      assert.equal(op, inp.prev_out)
      assert.equal("", inp.script_sig)
      assert.equal(0xFFFFFFFF, inp.sequence)
      assert.is_table(inp.witness)
      assert.equal(0, #inp.witness)
    end)

    it("creates a txin with custom values", function()
      local h = types.hash256(string.rep("\x00", 32))
      local op = types.outpoint(h, 1)
      local inp = types.txin(op, "script", 12345)

      assert.equal("script", inp.script_sig)
      assert.equal(12345, inp.sequence)
    end)
  end)

  describe("txout", function()
    it("creates a txout with defaults", function()
      local out = types.txout(50000)
      assert.equal("txout", out._type)
      assert.equal(50000, out.value)
      assert.equal("", out.script_pubkey)
    end)

    it("creates a txout with script", function()
      local out = types.txout(100000000, "\x76\xa9\x14")
      assert.equal(100000000, out.value)
      assert.equal("\x76\xa9\x14", out.script_pubkey)
    end)
  end)

  describe("transaction", function()
    it("creates a transaction with defaults", function()
      local tx = types.transaction()
      assert.equal("transaction", tx._type)
      assert.equal(1, tx.version)
      assert.is_table(tx.inputs)
      assert.equal(0, #tx.inputs)
      assert.is_table(tx.outputs)
      assert.equal(0, #tx.outputs)
      assert.equal(0, tx.locktime)
      assert.is_false(tx.segwit)
    end)

    it("creates a transaction with custom values", function()
      local h = types.hash256(string.rep("\x00", 32))
      local inp = types.txin(types.outpoint(h, 0))
      local out = types.txout(50000)
      local tx = types.transaction(2, {inp}, {out}, 500000)

      assert.equal(2, tx.version)
      assert.equal(1, #tx.inputs)
      assert.equal(1, #tx.outputs)
      assert.equal(500000, tx.locktime)
    end)
  end)

  describe("block_header", function()
    it("creates a block header with defaults", function()
      local hdr = types.block_header()
      assert.equal("block_header", hdr._type)
      assert.equal(1, hdr.version)
      assert.equal("hash256", hdr.prev_hash._type)
      assert.equal("hash256", hdr.merkle_root._type)
      assert.equal(0, hdr.timestamp)
      assert.equal(0, hdr.bits)
      assert.equal(0, hdr.nonce)
    end)

    it("creates a block header with custom values", function()
      local prev = types.hash256(string.rep("\x01", 32))
      local merkle = types.hash256(string.rep("\x02", 32))
      local hdr = types.block_header(4, prev, merkle, 1234567890, 0x1d00ffff, 2083236893)

      assert.equal(4, hdr.version)
      assert.equal(prev, hdr.prev_hash)
      assert.equal(merkle, hdr.merkle_root)
      assert.equal(1234567890, hdr.timestamp)
      assert.equal(0x1d00ffff, hdr.bits)
      assert.equal(2083236893, hdr.nonce)
    end)
  end)

  describe("block", function()
    it("creates a block with defaults", function()
      local hdr = types.block_header()
      local blk = types.block(hdr)
      assert.equal("block", blk._type)
      assert.equal(hdr, blk.header)
      assert.is_table(blk.transactions)
      assert.equal(0, #blk.transactions)
    end)

    it("creates a block with transactions", function()
      local hdr = types.block_header()
      local tx = types.transaction()
      local blk = types.block(hdr, {tx})

      assert.equal(1, #blk.transactions)
      assert.equal(tx, blk.transactions[1])
    end)
  end)
end)
