#!/usr/bin/env bash
# regen-shims.sh — (re)generate lunarblock/<f>.lua shim files from src/<f>.lua.
#
# The shims exist so require("lunarblock.<module>") resolves when running
# `luajit src/main.lua` directly (no rockspec install). Each shim just
# dofile()s the canonical src/<f>.lua. See tools/check-file-sync.sh for
# the enforcement rule.
#
# Usage:
#   tools/regen-shims.sh        # regenerate every shim from every src/*.lua
#
# Safe to re-run — overwrites existing shims only.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if [ ! -d src ]; then
  echo "regen-shims: no src/ directory at $REPO_ROOT" >&2
  exit 2
fi
mkdir -p lunarblock

count=0
for f in src/*.lua; do
  b="$(basename "$f")"
  name="${b%.lua}"
  out="lunarblock/$b"
  cat > "$out" <<EOF
-- Auto-generated shim. Canonical source is src/${b}.
-- DO NOT EDIT THIS FILE. Edit src/${b} instead.
-- Regenerate with: tools/regen-shims.sh
-- Enforced by:    tools/check-file-sync.sh
--
-- Rationale: running \`luajit src/main.lua\` without installing the rockspec
-- means \`require("lunarblock.${name}")\` resolves via luajit's default
-- \`./?.lua\` search pattern to this file. We forward to the canonical
-- src/ copy via dofile using a path derived from this shim's own location.
local dir = debug.getinfo(1, "S").source:match("@?(.*/)") or ""
return dofile(dir .. "../src/${b}")
EOF
  count=$((count + 1))
done

echo "regen-shims: wrote $count shims to lunarblock/"
